[package]
name = "clickrs_proc_macro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.6"
darling = "0.13.0"
proc-macro2 = "1.0"
structopt = "0.3"

[dependencies.syn]
version = "1.0.27"
features = ["full"]
